name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build JAR
      run: ./gradlew app-service:build
    - name: Build the Docker image
      run: docker build . --file ./deployment/Dockerfile --tag arc:$(date +%s)
    - shell: bash
      env:
        SUPER_SECRET: ${{ secrets.SECRET }}
      run: |
        echo "$SUPER_SECRET"
